### PR TITLE
Fixes wrong types in invoice create

### PR DESCRIPTION
**Pull request by elias-summermatter**

### CODE REVIEW

**Comment by elias-summermatter** [comment]
@mathewmeconry can you take a look and release it if ok? The type error makes the library not very usable.

**Comment by mathewmeconry** [comment]
Hey @elias-summermatter 
sorry busy time. I merged it and will release today

**Comment by mathewmeconry** [comment]
version 3.1.1 is released: https://www.npmjs.com/package/bexio

**Comment by elias-summermatter** [comment]
Tanks :-)

**Pull request merged**
